### ISSUE TITLE
Clarify Intent and Wording of License

### ISSUE THREAD

**Issue by brian-brazil** [DerbyBoutTime/bouttime#140]
Hi,

I applaud your goal of engaging the development community and pushing electronic tracking into a wider market. The current license on this software is however unclear and in my opinion overly restrictive, and thus directly at odds with this goal.

Taking an example, the preamble prohibition on commercial use means that leagues cannot use this software at any event where money is involved (such as ticket fees, tournament fees, vendor fees, merch sales, commercial broadcasting and the various other ways bouts are funded).

I would personally recommend going with a standard free software license, such as Apache 2.0. This will avoid problems of this nature, and by having a well known open and free license encourage contributions.

Barring that, can you please clarify:
1. What the intended type of license actually is
2. Exactly what changes you've made from the Apache 2.0 license
3. The contradictions between the preamble and the license itself?

To go into more detail https://wftda.com/news/wftda-releases-games-data-software-as-open-source-project indicates that this project has license modelled on Apache-2.0, however the LICENSE file says:

> The purpose of this license is to allow anyone to download and use BoutTime in connection with roller derby. This license does not allow you to redistribute derivative works based on the Work, or to use the Work commercially. This means that you are not allowed to sell copies of the Work (or derivative works based on the Work), or to package the Work within a product or service for sale, without the written consent of WFTDA.

This implies a restriction on use (roller derby only), a prohibition on commercial use, a prohibition on redistribution of derivative works, a prohibition on sale and a prohibition on packaging. None of these are in line with an Apache 2.0 license. In addition none of them appear to be stated in the license itself, and several are directly contradicted by the license text.

Also the license contains:

> and any modified versions of the Work must be subject to the terms of this License

which makes it a copyleft/viral license. The copyright grant in 2) has removed the clause about being "irrevocable". Neither of these are like an Apache license, and the latter may also be in contention with of Github's terms of service in that you must permit users to view and fork.

Restrictive licenses discourage both use and contributions from the development community, and are not what I'd expect from an organisation whose mission is to promote and foster goodwill among member leagues. Unusual licenses also discourage potential users and contributors, as not everyone has the time to dig into the implications of a non-standard license.

On a typographical note, there's two of section 4(c).

**Comment by kweerious** [comment]
Thanks for opening the discussion on this issue. I'd like to say upfront, that we really like the Apache 2.0 license and think it covers a lot of what we are going for here. But the non-commercial language was a long internal discussion. You'll notice that most of the contributions to this repo were made last year, in the meantime we've been back and forth with legal and leadership on how to get this out and open.

There's a concern that we cannot remedy at the moment about our status as a 501c3 non-profit and the distribution of open source as it relates to tax liability and continuing to operate as a non-profit.<sup>1</sup>, <sup>2</sup> We are still working with the IRS in the hopes that we can revisit this in the future.

Our intent with this license can be summed up as follows:

- Anyone can download this and use it in the service of playing roller derby. 
- Like the Rules, every bit of our creation is exposed for the public to see, make a copy of, and tinker with. 
- If you tinker with it, we hope you'll push those contributions back up to WFTDA so we can review and maybe integrate your suggestions. (Likewise, if you change a couple rules for home season play, we hope you'll push those back upstream via TimeOut and the Rules revision process.)
- You can tinker with our product, and distribute your tinkering if you credit WFTDA and mark your modifications. 
- You may not create a derivative work that you claim is a wholly different product with different authorship.
- You cannot distribute our original product, or a version with your modifications, commercially, without our written consent.

I'll have to get back to you on the preamble and the typo.

[1] IRS rulings: https://wiki.opensource.org/bin/Main/Projects/entities-wg/IRS+Ruling+Documentation/#HPLR20140502428providerofCreativeCommons-licensededucationalmaterials29
[2] https://www.techdirt.com/articles/20140701/11470827745/irs-rejects-non-profit-status-open-source-organization-because-private-companies-might-use-software.shtml

**Comment by brian-brazil** [comment]
I have contacts in the Linux Foundation (and some people in the FSF might remember me still). Would you like me to reach out to them to see if anything can be done around the commercial aspects? Given WFTDA is a sport rather than software-focused organisation I imagine it might be easier.

As something to do now, I'd suggest removing the mention of Apache 2.0 on https://wftda.com/news/wftda-releases-games-data-software-as-open-source-project as this is only superficially an Apache 2.0 license and thus it is very misleading.

**Comment by kweerious** [comment]
@brian-brazil if you are willing to investigate, we are listening.

As for the mention of the Apache 2.0 license, I think it's at least helpful in projecting what we _want_ to achieve even if we aren't quite there yet. If it's not offensive, I think we might just leave it in that blog post and in this discussion as we try to rectify the differences.

**Comment by brian-brazil** [comment]
> If you are willing to investigate, we are listening.

I'll reach out, but I can't promise anything.

> If it's not offensive, I think we might just leave it in that blog post and in this discussion as we try to rectify the differences.

I don't understanding how the contradictions between the announcement, preamble, license and this issue would be handled. This is probably a good time to talk to a lawyer, which I am not.

**Comment by brian-brazil** [comment]
It looks like licensing@fsf.org is the FSF address for this sort of question. It's probably best to email them directly, rather than me getting in the way as a middleman.

**Comment by kweerious** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolve License concerns](https://trello.com/c/oKmSEFe4/52-resolve-license-concerns)

**Comment by brian-brazil** [comment]
I got a response from my contact in the Linux Foundation:

> So prohibiting commercial usage would completely against what is considered an OSI certified license:
https://opensource.org/faq#commercial

> By the way, the best place to ask this question IMHO would be license-discuss in the OSI:
https://opensource.org/lists

> Their 501(c)(3) status won't be affected by using an OSI certified license. As an example, Apache Foundation and LetsEncrypt are both 501(c)(3)s

**Comment by kweerious** [comment]
I doubled checked with the BoD, they made similar inquiries with a similar response but with the additional guidance to seek a second opinion (which we are pursuing including contacting the IRS).

**Comment by akeyes** [comment]
Any updates on this?

**Comment by kweerious** [comment]
@akeyes I'll try to get a status on this but some aspects of our NPO status are being reviewed so an definitive answer might take a bit longer.
